in tests, build reqewest::Client with no_proxy
That *appears* to be the cause for this failure on darwin:

```
thread '<unnamed>' (103071) panicked at /nix/build/nix-5646-2352996470/mdfried-0.20.1-vendor/source-registry-0/system-configuration-0.5.1/src/dynamic_store.rs:154:1:
Attempted to create a NULL object.
```

See also: `cargo tree -i system-configuration --target all`.